### ISSUE TITLE
Strange DMSG messages

### ISSUE THREAD

**Issue by ciclopeblu** [steverydz/notion-snap#1]
I have installed notion-snap - I'm getting this dmsg:

[  991.658604] audit: type=1400 audit(1614419291.406:80): apparmor="DENIED" operation="rmdir" profile="snap.notion-snap.notion-snap" name="/mnt/nextcloud/Documents/" pid=15417 comm="rmdir" requested_mask="d" denied_mask="d" fsuid=1000 ouid=1000

Should I be concerned?

**Comment by steverydz** [comment]
I don't think there is any reason for concern. I imagine this is something to do with electron as I get the same message for other electron based apps I have installed, for example Todoist.
