### ISSUE TITLE
Cannot authent with google

### ISSUE THREAD

**Issue by CorentinJak** [steverydz/notion-snap#2]
When submitting my email during google Authent :
A message appeared to indicate the browser or application are not safe.
![image](https://user-images.githubusercontent.com/52312278/113403054-597ab400-93a6-11eb-82aa-b491f5584590.png)

System :
- Ubuntu 20.04.2 LTS
- Type : 64 bits
- Gnome : 3.36.8
- Window sys : X11

Notion-snap installed with Ubuntu-software.

**Comment by steverydz** [comment]
Thanks for reporting this issue. It seems to be the way Google auth behaves in an electron app. There is a solution that uses an external datastore but that is way beyond the scope of this app. I'm hoping that Notion will eventually create their own snap which will handle issues like these.
