### ISSUE TITLE
Cannot use two windows

### ISSUE THREAD

**Issue by LucasDondo** [steverydz/notion-snap#3]
Hi Steve, this project is excellent, it works nicely! The only problem I encountered for the moment (I've been using it for a few days now) is that when I open a new window (I know there is no option to do so within the app itself, but through the ZorinOS panel, it's possible), this error appears in that second window:
![Cannot save changes - Notion snap](https://user-images.githubusercontent.com/59975541/114711764-b743c000-9d05-11eb-8cbe-eefba13d518b.png)
Also, after opening that window, the only way to close it is by closing it with a task manager.

**Comment by steverydz** [comment]
Thanks Lucas. I'll look into this when time allows.

**Comment by PedroLima92** [comment]
I've found that if you `ctrl`+`click`, as one would do to get a 'new tab', you can get multiple windows with no problem. One minor inconvenience is that they seem to keep a hierarchy, so if you close the window A from where you `ctrl`+`click`ed window B into existence, you're going to close them both.

**Comment by LucasDondo** [comment]
You are totally right! I never thought about it. I'll now close this issue since it is no a problem anymore (at least with this workaround).
