### ISSUE TITLE
Notion-snap opens links in itself, not in the default browser.

### ISSUE THREAD

**Issue by weakiam** [steverydz/notion-snap#7]
Notion-snap opens links in itself, not in the default browser.
I don't know if it is a feature or a bug, but I would like to modify that if possible. 
![Screenshot from 2022-06-16 19-26-52](https://user-images.githubusercontent.com/107641835/174130791-e8bf80b8-a5f0-4326-8d25-b0da1d2c8365.png)
Links like this.

**Comment by gauchya** [comment]
Hello,
I have the same problem on Ubuntu 22.04.
If it's possible I think external links should open in default system browser.

**Comment by Lukewh** [comment]
This has been released to the stable channel as version 1.4.0. Reopen this issue if anyone finds an issue :).
