### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by ju4ncito** [steverydz/notion-snap#9]
Coould not find any options regarding spell-check so I can turn it off. Is there any config file I can change?

**Comment by steverydz** [comment]
It looks like there is [a solution for this in electron](https://www.electronjs.org/docs/latest/tutorial/spellchecker). I'm inclined to think that perhaps this should be disabled globally as it is essentially a browser feature.

**Comment by kbrannen** [comment]
The reverse of this is also true. :) It'd be really nice to have a functioning spellcheck, where you can right-click on the misspelled word and be offered suggestions to change it to ... just like the app does when on Windows.

[BTW, thanks for doing this work so we can have Notion on Linux until Notion.so gets around to it!]
